### ISSUE TITLE
side_exit_sensor.stl is a duplicate of side_exit_mag.stl

### ISSUE THREAD

**Issue by Tabby** [GeekyDeaks/g29-hall-sensor-mod#2]
I just noticed that side_exit_sensor.stl is a duplicate of side_exit_mag.stl and not actually the sensor housing at all >_<

This mod looks great though and I look forward to trying it :)

**Comment by GeekyDeaks** [comment]
Doh! I thought I had fixed that ages ago!  Just pushed the changes in bc9f145

**Comment by Tabby** [comment]
That was fast! Thanks very much 😁
